### ISSUE TITLE
地方台 - 苏州可以更新一下吗？

### ISSUE THREAD

**Issue by justgues** [suxuang/myIPTV#14]
以下三个原地址打不开
苏州新闻综合,http://tylive.kan0512.com/norecord/norecord_csztv1.m3u8
苏州社会经济,http://tylive.kan0512.com/norecord/norecord_csztv2.m3u8
苏州文化生活,http://tylive.kan0512.com/norecord/norecord_csztv3.m3u8
增加下面一个
苏州生活资讯 http://tylive.kan0512.com/norecord/norecord_csztv5.m3u8

**Comment by suxuang** [comment]
好的，已更新
