### ISSUE TITLE
ok 2.5.9  获取源失败

### ISSUE THREAD

**Issue by alexlipe** [suxuang/myIPTV#35]
ok 2.5.9  获取源失败。 提示配置获取失败  length=1;index=1

**Comment by alexlipe** [comment]
找到失败原因了， 是因为咪咕的地址中最后的参数 $订阅源|1920x1080 。 去掉后就可以正常加载了

**Comment by suxuang** [comment]
我更新一下发自我的 iPhone在 2024年11月23日，23:46，alexlipe ***@***.***> 写道：﻿
找到失败原因了， 是因为咪咕的地址中最后的参数 $订阅源|1920x1080 。 去掉后就可以正常加载了
